### PR TITLE
docs(api): add folder structure for orca service api

### PR DESCRIPTION
**Pull request by brian-armory**
Creates the folder structure that https://github.com/spinnaker/orca/pull/4198 uses. After Orca 4198 is merged and a page is generated, following should happen:

1) Merge the PR for the autogenerated page in this repo (if necessary)
2) Consume the updates  by merging master into this PR
3) Verify that the page shows up where we expect in the deploy preview:

https://deploy-preview-162--spinnaker-io.netlify.app/docs/reference/api/service-plugin-apis/orca-api/

image

### CODE REVIEW

**Review by dbyron-sf — APPROVED** [review]

**Comment by mattgogerly** [comment]
@Mergifyio update

**Comment by mattgogerly** [comment]
@brian-armory @dbyron-sf  are you expecting to see content on the master page?

**Comment by dbyron-sf** [comment]
> @brian-armory @dbyron-sf are you expecting to see content on the master page?

Not yet...I don't think https://github.com/spinnaker/orca/blob/2379f14ecb0d063169e09fd448cae7d856fcd4fe/.github/workflows/docs_master.yml is successfully making PRs yet.  I haven't tracked down exactly what's failing...see e.g. https://github.com/spinnaker/orca/runs/4693742508?check_suite_focus=true

**Comment by brian-armory** [comment]
I'll go ahead and merge this first since all it does is add the folder structure.

**Pull request merged**
