### PR TITLE
Redesign Progress

### PR DESCRIPTION
**Pull request by prophen**
I've gotten to a point where I can ask for feedback. 
Please provide your comments/feedback by Tuesday, June 8th 🙏🏾

## It's helpful to include the following (as applicable) with your feedback
- Description/screenshots
- URL
- browser/os
- Expected or desired behavior
- Impact if not addressed
- Priority (P1 - blocking do not ship, P2 - ideally fix pre-launch but not blocking, P3 - fix but not high priority, P4 - idea for later) -- for criteria think about the impact of the users of the site 

[Thanks, Jennifer for the guidelines]

### CODE REVIEW

**Comment by aimeeu** [comment]
This looks great!!

**Comment by ericmikkelsen** [comment]
This is so good! I seriously love that you're not using a hamburger menu.

I did a quick [lighthouse test](https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fdeploy-preview-83--spinnaker-io.netlify.app%2F), from what I'm seeing you could spare download time by using svg(vector) versions of the logos. 

I grabbed this one off the glovo site, and it pulls about a 1mb off the site. 
[glovo-logo.svg.zip](https://github.com/spinnaker/spinnaker.io/files/6588454/glovo-logo.svg.zip)

If you need some help pulling them off off websites etc, I'm a little nerdy about hunting them down and would love to help out (but also understand if that's not what your looking for).

**Comment by prophen** [comment]
> This is so good! I seriously love that you're not using a hamburger menu.
> 
> I did a quick [lighthouse test](https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fdeploy-preview-83--spinnaker-io.netlify.app%2F), from what I'm seeing you could spare download time by using svg(vector) versions of the logos.
> 
> I grabbed this one off the glovo site, and it pulls about a 1mb off the site.
> [glovo-logo.svg.zip](https://github.com/spinnaker/spinnaker.io/files/6588454/glovo-logo.svg.zip)
> 
> If you need some help pulling them off off websites etc, I'm a little nerdy about hunting them down and would love to help out (but also understand if that's not what your looking for).

OMG, yes! That is exactly the kind of help I was looking for. If you take on searching for logos can you also look out for the longer ones over the square shaped ones? 

The way we have it now, the square logos look more prominent

**Comment by prophen** [comment]
I checked on my mobile phone and saw this bug. Will try to resolve today 
2B6A7139-FC94-4FA0-A4CA-48949FB6A79A

**Comment by bbrina** [comment]
Looks great! 🥳

Just some humble thoughts...

1) Maybe adding a background image to make the hero eye catching?
Screen Shot 2021-06-03 at 12 29 38

2) I feel like this section is just a huge block of information that doesn't invite the user to stick around and read it. Maybe shortening the descriptions and adding some icons to each section to make it more digestible?

Screen Shot 2021-06-03 at 12 29 46

**Review by dogonthehorizon — COMMENTED** [review]
Looking great! I spot checked a few pages and most things look correct.

I did find one thing, however, and I'm not sure whether this is related to Netlify or an actual issue. The Next Steps links at the bottom of this page are not rendering correctly:
https://deploy-preview-83--spinnaker-io.netlify.app/docs/guides/developer/plugin-creator/plugin-frontend/

Screenshot:
image

**Comment by brian-armory** [comment]
> Looking great! I spot checked a few pages and most things look correct.
> 
> I did find one thing, however, and I'm not sure whether this is related to Netlify or an actual issue. The Next Steps links at the bottom of this page are not rendering correctly:
> [deploy-preview-83--spinnaker-io.netlify.app/docs/guides/developer/plugin-creator/plugin-frontend](https://deploy-preview-83--spinnaker-io.netlify.app/docs/guides/developer/plugin-creator/plugin-frontend/)
> 
> Screenshot:
> image

Woops. Those are missing a { bracket. I'll fix that.

**Comment by brian-armory** [comment]
It looks much more modern! 

P3 - The only thing I see so far is that it's a little jarring that the logo walls (on the home page and community) are clickable and drops the user back at the top of the home page. Also on the supported cloud providers, app engine is part of GCP, so it can probably be removed.

After this, the outstanding things are porting the releases page(s) and the auto generated pages, right? Was there anything else?

**Comment by brian-armory** [comment]
🤦🏼 GitHub tried to get too smart for itself and closed this. I reopened it. Sorry.

**Comment by ericmikkelsen** [comment]
> > This is so good! I seriously love that you're not using a hamburger menu.
> > I did a quick [lighthouse test](https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fdeploy-preview-83--spinnaker-io.netlify.app%2F), from what I'm seeing you could spare download time by using svg(vector) versions of the logos.
> > I grabbed this one off the glovo site, and it pulls about a 1mb off the site.
> > [glovo-logo.svg.zip](https://github.com/spinnaker/spinnaker.io/files/6588454/glovo-logo.svg.zip)
> > If you need some help pulling them off off websites etc, I'm a little nerdy about hunting them down and would love to help out (but also understand if that's not what your looking for).
> 
> OMG, yes! That is exactly the kind of help I was looking for. If you take on searching for logos can you also look out for the longer ones over the square shaped ones?
> 
> The way we have it now, the square logos look more prominent

@prophen I can totally keep an eye out for that, I can probably get that to you today or tomorrow.

**Comment by justjenu** [comment]
@prophen this is looking great! 

I agree about the background image on the hero and the design of the features list - what about making the features list similar to the treatment of Automated Releases, etc. in the section above? I will get you an image for the hero.

- [ ] P2: On home page the background color for supported cloud providers is not accessible with the logos on top of it - the color there should be adjusted to make sure that it is easy to read and the color meets the accessibility requirements
- [ ] P2: Powered by Spinnaker logo links - I would expect those to link individually to each company or not at all - definitely not to link to the current page
- [ ] P2: Can you add a "?" after "Who should use Spinnaker" so it is dramatically correct?
- [ ] P2: On /docs/community "The Spinnaker OSS project was started at Netflix. Now, it thrives on the contributions of the broader DevOps community who have adopted it as their Continuous Delivery tool." shouldn't be repeated.

**Comment by prophen** [comment]
> Looks great! 🥳
> 
> Just some humble thoughts...
> 
>  1. Maybe adding a background image to make the hero eye catching? 
> 1. I feel like this section is just a huge block of information that doesn't invite the user to stick around and read it. Maybe shortening the descriptions and adding some icons to each section to make it more digestible?
> 
> 

Thanks for leaving feedback, Barbara. I added a hero image and broke the features list into cards.

**Comment by prophen** [comment]
> @prophen this is looking great!
> 
> I agree about the background image on the hero and the design of the features list - what about making the features list similar to the treatment of Automated Releases, etc. in the section above? I will get you an image for the hero.
> 
>     * [ ]  P2: On home page the background color for supported cloud providers is not accessible with the logos on top of it - the color there should be adjusted to make sure that it is easy to read and the color meets the accessibility requirements
> 
>     * [ ]  P2: Powered by Spinnaker logo links - I would expect those to link individually to each company or not at all - definitely not to link to the current page
> 
>     * [ ]  P2: Can you add a "?" after "Who should use Spinnaker" so it is dramatically correct?
> 
>     * [ ]  P2: On /docs/community "The Spinnaker OSS project was started at Netflix. Now, it thrives on the contributions of the broader DevOps community who have adopted it as their Continuous Delivery tool." shouldn't be repeated.

I addressed each point in the latest design. Thanks, @justjenu

**Comment by prophen** [comment]
Hi @brian-armory, @aimeeu please review.

**Comment by prophen** [comment]
@ajordens Can this repo be updated to match the permissions on the other Spinnaker repositories? We are nearly ready to launch https://deploy-preview-83--spinnaker-io.netlify.app/ but need this repo locked down to go live

**Review by brian-armory — APPROVED** [review]
We didn't review every changed file, but we've done some basic verification to make sure everything major is in a good enough state so that there is parity between this and the current live site. 

Based on that, approving. There is some outstanding work that Nikema will follow up on with knowledgable community members.

**Review by aimeeu — APPROVED** [review]

**Pull request merged**
